--------------------------------------------------------------------------------
-- Inertial_3d Component Tester Spec
--------------------------------------------------------------------------------

-- Includes:
with Component.Inertial_3d_Reciprocal;
with Printable_History;
with Data_Product.Representation;
with Data_Product;
with Att_Ref.Representation;

-- Inertial 3D algorithm produces a fixed inertial attitude reference message. The
-- reference attitude is immutable algorithm configuration supplied as a
-- parameter, not a per-tick input.
package Component.Inertial_3d.Implementation.Tester is

   use Component.Inertial_3d_Reciprocal;
   -- Invoker connector history packages:
   package Data_Product_T_Recv_Sync_History_Package is new Printable_History (Data_Product.T, Data_Product.Representation.Image);

   -- Data product history packages:
   package Attitude_Reference_History_Package is new Printable_History (Att_Ref.T, Att_Ref.Representation.Image);

   -- Component class instance:
   type Instance is new Component.Inertial_3d_Reciprocal.Base_Instance with record
      -- The component instance under test:
      Component_Instance : aliased Component.Inertial_3d.Implementation.Instance;
      -- Connector histories:
      Data_Product_T_Recv_Sync_History : Data_Product_T_Recv_Sync_History_Package.Instance;
      -- Data product histories:
      Attitude_Reference_History : Attitude_Reference_History_Package.Instance;
   end record;
   type Instance_Access is access all Instance;

   ---------------------------------------
   -- Initialize component heap variables:
   ---------------------------------------
   procedure Init_Base (Self : in out Instance);
   procedure Final_Base (Self : in out Instance);

   ---------------------------------------
   -- Test initialization functions:
   ---------------------------------------
   procedure Connect (Self : in out Instance);

   ---------------------------------------
   -- Invokee connector primitives:
   ---------------------------------------
   -- The data product invoker connector.
   overriding procedure Data_Product_T_Recv_Sync (Self : in out Instance; Arg : in Data_Product.T);

   -----------------------------------------------
   -- Data product handler primitives:
   -----------------------------------------------
   -- Description:
   --    Data products for the Inertial 3D component.
   -- Fixed inertial attitude reference generated by the algorithm.
   overriding procedure Attitude_Reference (Self : in out Instance; Arg : in Att_Ref.T);

   -----------------------------------------------
   -- Special primitives for aiding in the staging,
   -- fetching, and updating of parameters
   -----------------------------------------------
   -- Stage a parameter value within the component
   not overriding function Stage_Parameter (Self : in out Instance; Par : in Parameter.T) return Parameter_Update_Status.E;
   -- Fetch the value of a parameter with the component
   not overriding function Fetch_Parameter (Self : in out Instance; Id : in Parameter_Types.Parameter_Id; Par : out Parameter.T) return Parameter_Update_Status.E;
   -- Ask the component to validate all parameters. This will call the
   -- Validate_Parameters subprogram within the component implementation,
   -- which allows custom checking of the parameter set prior to updating.
   not overriding function Validate_Parameters (Self : in out Instance) return Parameter_Update_Status.E;
   -- Tell the component it is OK to atomically update all of its
   -- working parameter values with the staged values.
   not overriding function Update_Parameters (Self : in out Instance) return Parameter_Update_Status.E;

end Component.Inertial_3d.Implementation.Tester;
