name: Check Style (ARM64)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:
jobs:
  compile_job:
    name: style_all (arm64)
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting job triggered by a ${{ github.event_name }} event on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "Checking out ${{ github.repository }} on branch ${{ github.ref }}."

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          set-safe-directory: true
          path: adamant-xmera-components

      - name: Clone adamant repository
        uses: actions/checkout@v4
        with:
          set-safe-directory: true
          repository: lasp/adamant
          path: adamant

      - name: Clone adamant repository
        uses: actions/checkout@v4
        with:
          set-safe-directory: true
          repository: lasp/fp32-fsw-xmera
          path: fp32-fsw-xmera

      - name: Clone Eigen 3.4.1 from GitLab
        run: |
          git clone --depth 1 --branch 3.4.1 https://gitlab.com/libeigen/eigen.git eigen

      - name: Check all style
        run: |
          docker run --rm --platform linux/arm64 \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            -e TMPDIR=/tmp \
            -e ADAMANT_TMP_DIR=/tmp/.adamant \
            ghcr.io/lasp/adamant:0.1 \
            bash adamant-xmera-components/env/github_run.sh "redo adamant-xmera-components/style_all"
        # NOTE: TMPDIR and ADAMANT_TMP_DIR must be set to the container's native filesystem (/tmp)
        # rather than the volume-mounted workspace. This prevents cross-device I/O errors with the
        # redo build system's unqlite database and Python's shutil.move() operations.

      - name: Archive logs for failed style checks
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: style_logs_arm64
          path: ${{ github.workspace }}/adamant-xmera-components/build
          if-no-files-found: ignore

      - run: echo "Finished with status - ${{ job.status }}."
        if: always()
